/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecommercesystem;

import javax.swing.JFrame;

/**
 *
 * @author salsa
 */
public class EcommerceSystem extends javax.swing.JFrame {
   BookProduct p3 = new BookProduct();
   ElectronicProduct p1 = new ElectronicProduct();
     ClothingProduct p2 = new ClothingProduct();
     Customer customer = new Customer();
    Cart cart = new Cart();
    Order order = new Order();
   static int phonesnumber = 0;
   static int tshirtsnumber = 0;
   static int booksnumber = 0;
   static float totalPrice = 0;
   static float phonesPrice = 0;
   static float tshirtsPrice = 0;
   static float booksPrice = 0;
   
   
    


    
    public EcommerceSystem() {
        initComponents();
        this.setLocationRelativeTo(null);
       
      
       
        // product#1-----------------------------------
         
    p1.setName("smartphone");
    p1.setProductId(1);
    p1.setPrice(599.9f);
    p1.setBrand("Samsung");
    p1.setWarrantyPeriod(1);
    // product#2-----------------------------
   
    p2.setName("T-shirt");
    p2.setProductId(2);
    p2.setPrice(19.99f);
    p2.setSize("Medium");
    p2.setFabric("Cotton");
    // product#3-----------------------------
   
    p3.setName("OOP");
    p3.setProductId(3);
    p3.setPrice(39.99f);
    p3.setAuthor("O'Reilly");
    p3.setPublisher("X Publications");
    //to make it in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taps = new javax.swing.JTabbedPane();
        login = new keeptoo.KGradientPanel();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        errorLogin = new javax.swing.JLabel();
        product = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_tocart = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        phonePrice = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        plusphone = new javax.swing.JButton();
        minphone = new javax.swing.JButton();
        phonenum = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        mintshirt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tshirtPrice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        plustshirt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tshirtnum = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        minbook = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        bookPrice = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        plusbook = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        booknum = new javax.swing.JLabel();
        total_in_products = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        hi = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        yourCart = new keeptoo.KGradientPanel();
        jLabel27 = new javax.swing.JLabel();
        total_tshirt_price_cart = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tshirt_quantity_cart = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        phone_quantity_cart = new javax.swing.JLabel();
        total_phone_price_cart = new javax.swing.JLabel();
        book_quantity_cart = new javax.swing.JLabel();
        btn_place_order = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        total_in_products1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        total1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        total_book_price_cart = new javax.swing.JLabel();
        orderSummary = new keeptoo.KGradientPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tshirt_quantity_cart1 = new javax.swing.JLabel();
        phone_quantity_cart1 = new javax.swing.JLabel();
        book_quantity_cart1 = new javax.swing.JLabel();
        total_in_products2 = new javax.swing.JLabel();
        btn_sumbit = new javax.swing.JButton();
        total_phone_price_cart1 = new javax.swing.JLabel();
        total_tshirt_price_cart1 = new javax.swing.JLabel();
        total_book_price_cart1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        name_in_receipt = new javax.swing.JLabel();
        id_in_receipt = new javax.swing.JLabel();
        address_in_receipt = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        thanku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-commerce System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taps.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        taps.setDoubleBuffered(true);

        login.setkEndColor(new java.awt.Color(0, 153, 153));
        login.setkStartColor(new java.awt.Color(51, 255, 102));

        btn_login.setBackground(new java.awt.Color(147, 124, 90));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Welcome to E-commerce System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");

        errorLogin.setForeground(new java.awt.Color(255, 51, 51));
        errorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(errorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(errorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        taps.addTab("tab4", login);

        product.setkEndColor(new java.awt.Color(0, 153, 153));
        product.setkStartColor(new java.awt.Color(51, 255, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Our Products");

        btn_tocart.setBackground(new java.awt.Color(167, 146, 119));
        btn_tocart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_tocart.setForeground(new java.awt.Color(255, 255, 255));
        btn_tocart.setText("ADD TO CART");
        btn_tocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tocartActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(167, 146, 119));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("SMARTPHONE");

        phonePrice.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        phonePrice.setForeground(java.awt.Color.white);
        phonePrice.setText("price : $599.9");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("393 ppi  Infinity-O Display");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Super AMOLED Plus(2400x1080) ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Battery Capacity:4300mAh ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Dimension:161.6 x 75.2 x 8.3mm");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Display: 20 6.7'' flat FHD+ ");

        plusphone.setBackground(new java.awt.Color(0, 255, 0));
        plusphone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plusphone.setText("+");
        plusphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusphoneActionPerformed(evt);
            }
        });

        minphone.setBackground(new java.awt.Color(255, 0, 0));
        minphone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minphone.setText("-");
        minphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minphoneActionPerformed(evt);
            }
        });

        phonenum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phonenum.setForeground(java.awt.Color.white);
        phonenum.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(minphone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phonenum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(plusphone, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phonePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phonePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusphone)
                    .addComponent(minphone)
                    .addComponent(phonenum))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(167, 146, 119));

        mintshirt.setBackground(new java.awt.Color(255, 0, 0));
        mintshirt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mintshirt.setText("-");
        mintshirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mintshirtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Fabric : cotton");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Men and women");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("color : black");

        tshirtPrice.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tshirtPrice.setForeground(java.awt.Color.white);
        tshirtPrice.setText("price : $19.99");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("T-SHIRT");

        plustshirt.setBackground(new java.awt.Color(0, 255, 0));
        plustshirt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plustshirt.setText("+");
        plustshirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plustshirtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("size : medium");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText(" Rounded neck t-shirt for both");

        tshirtnum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tshirtnum.setForeground(java.awt.Color.white);
        tshirtnum.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(mintshirt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tshirtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(plustshirt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(tshirtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9))
                                .addGap(78, 78, 78))))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(tshirtPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plustshirt)
                    .addComponent(mintshirt)
                    .addComponent(tshirtnum))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(167, 146, 119));

        minbook.setBackground(new java.awt.Color(255, 0, 0));
        minbook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minbook.setText("-");
        minbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minbookActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("for the author O'Reilly");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("OOP book for learning ");

        bookPrice.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        bookPrice.setForeground(java.awt.Color.white);
        bookPrice.setText("price : $39.99");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("BOOK");

        plusbook.setBackground(new java.awt.Color(0, 255, 0));
        plusbook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plusbook.setText("+");
        plusbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusbookActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("object-orianted programming");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("Published by X Publications");

        booknum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        booknum.setForeground(java.awt.Color.white);
        booknum.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(minbook, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(booknum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(plusbook, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel25))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(bookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 3, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel24))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel20)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(50, 50, 50)
                .addComponent(bookPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusbook)
                    .addComponent(minbook)
                    .addComponent(booknum))
                .addContainerGap())
        );

        total_in_products.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        total_in_products.setForeground(new java.awt.Color(255, 255, 255));
        total_in_products.setText("Total  :");

        total.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));

        hi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hi.setForeground(new java.awt.Color(255, 255, 255));

        error.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout productLayout = new javax.swing.GroupLayout(product);
        product.setLayout(productLayout);
        productLayout.setHorizontalGroup(
            productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(productLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productLayout.createSequentialGroup()
                        .addComponent(total_in_products, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tocart, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        productLayout.setVerticalGroup(
            productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_in_products, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tocart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        taps.addTab("tab4", product);

        yourCart.setkEndColor(new java.awt.Color(0, 153, 153));
        yourCart.setkStartColor(new java.awt.Color(51, 255, 102));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(java.awt.Color.white);
        jLabel27.setText("Product              Quantaty              Price      ");

        total_tshirt_price_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_tshirt_price_cart.setForeground(java.awt.Color.white);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(java.awt.Color.white);
        jLabel28.setText("T-SHIRT");

        tshirt_quantity_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tshirt_quantity_cart.setForeground(java.awt.Color.white);
        tshirt_quantity_cart.setText("0");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(java.awt.Color.white);
        jLabel30.setText("SMARTPHONE");

        phone_quantity_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_quantity_cart.setForeground(java.awt.Color.white);
        phone_quantity_cart.setText("0");

        total_phone_price_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_phone_price_cart.setForeground(java.awt.Color.white);

        book_quantity_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book_quantity_cart.setForeground(java.awt.Color.white);
        book_quantity_cart.setText("0");

        btn_place_order.setBackground(new java.awt.Color(167, 146, 119));
        btn_place_order.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_place_order.setForeground(new java.awt.Color(255, 255, 255));
        btn_place_order.setText("PLACE YOUR ORDER");
        btn_place_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_place_orderActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("YOUR CART: ");

        total_in_products1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        total_in_products1.setForeground(java.awt.Color.white);
        total_in_products1.setText("Total : ");

        btn_back.setBackground(new java.awt.Color(255, 0, 0));
        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("back");
        btn_back.setBorder(null);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        total1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        total1.setForeground(java.awt.Color.white);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("OOP BOOK");

        total_book_price_cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_book_price_cart.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout yourCartLayout = new javax.swing.GroupLayout(yourCart);
        yourCart.setLayout(yourCartLayout);
        yourCartLayout.setHorizontalGroup(
            yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourCartLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yourCartLayout.createSequentialGroup()
                        .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(yourCartLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel30))
                                .addGap(124, 124, 124)
                                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone_quantity_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tshirt_quantity_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book_quantity_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118)
                                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(total_phone_price_cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total_tshirt_price_cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total_book_price_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(yourCartLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourCartLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_place_order, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourCartLayout.createSequentialGroup()
                                .addComponent(total_in_products1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)))))
                .addGap(33, 33, 33))
        );
        yourCartLayout.setVerticalGroup(
            yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yourCartLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total_in_products1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel27)
                .addGap(31, 31, 31)
                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_quantity_cart)
                    .addComponent(jLabel30)
                    .addComponent(total_phone_price_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tshirt_quantity_cart)
                    .addComponent(total_tshirt_price_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(yourCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(book_quantity_cart)
                    .addComponent(total_book_price_cart, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btn_place_order, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        taps.addTab("tab4", yourCart);

        orderSummary.setkEndColor(new java.awt.Color(0, 153, 153));
        orderSummary.setkStartColor(new java.awt.Color(51, 255, 102));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Product              Quantaty              Price      ");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Name :");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ID :");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Address :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("SMARTPHONE");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("T-SHIRT");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("OOP BOOK");

        tshirt_quantity_cart1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tshirt_quantity_cart1.setForeground(new java.awt.Color(255, 255, 255));
        tshirt_quantity_cart1.setText("0");

        phone_quantity_cart1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_quantity_cart1.setForeground(new java.awt.Color(255, 255, 255));
        phone_quantity_cart1.setText("0");

        book_quantity_cart1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        book_quantity_cart1.setForeground(new java.awt.Color(255, 255, 255));
        book_quantity_cart1.setText("0");

        total_in_products2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        total_in_products2.setForeground(new java.awt.Color(255, 255, 255));
        total_in_products2.setText("Total : ");

        btn_sumbit.setBackground(new java.awt.Color(167, 146, 119));
        btn_sumbit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sumbit.setForeground(new java.awt.Color(255, 255, 255));
        btn_sumbit.setText("SUMBIT");
        btn_sumbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumbitActionPerformed(evt);
            }
        });

        total_phone_price_cart1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_phone_price_cart1.setForeground(new java.awt.Color(255, 255, 255));

        total_tshirt_price_cart1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_tshirt_price_cart1.setForeground(new java.awt.Color(255, 255, 255));

        total_book_price_cart1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_book_price_cart1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Order Summary");

        name_in_receipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name_in_receipt.setForeground(new java.awt.Color(255, 255, 255));

        id_in_receipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id_in_receipt.setForeground(new java.awt.Color(255, 255, 255));

        address_in_receipt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address_in_receipt.setForeground(new java.awt.Color(255, 255, 255));

        total2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        total2.setForeground(new java.awt.Color(255, 255, 255));

        thanku.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        thanku.setForeground(new java.awt.Color(0, 255, 0));
        thanku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout orderSummaryLayout = new javax.swing.GroupLayout(orderSummary);
        orderSummary.setLayout(orderSummaryLayout);
        orderSummaryLayout.setHorizontalGroup(
            orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderSummaryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total_in_products2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(orderSummaryLayout.createSequentialGroup()
                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderSummaryLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel36)
                        .addGap(55, 55, 55)
                        .addComponent(thanku, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderSummaryLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderSummaryLayout.createSequentialGroup()
                                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address_in_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_in_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(orderSummaryLayout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_in_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderSummaryLayout.createSequentialGroup()
                                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33))
                                .addGap(124, 124, 124)
                                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone_quantity_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tshirt_quantity_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book_quantity_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118)
                                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(total_phone_price_cart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total_tshirt_price_cart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total_book_price_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(orderSummaryLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btn_sumbit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderSummaryLayout.setVerticalGroup(
            orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSummaryLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thanku, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jLabel29)
                .addGap(51, 51, 51)
                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderSummaryLayout.createSequentialGroup()
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone_quantity_cart1)
                            .addComponent(jLabel31)
                            .addComponent(total_phone_price_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tshirt_quantity_cart1)
                            .addComponent(total_tshirt_price_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(book_quantity_cart1)
                            .addComponent(total_book_price_cart1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(orderSummaryLayout.createSequentialGroup()
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_in_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_in_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address_in_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderSummaryLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btn_sumbit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderSummaryLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(orderSummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total_in_products2)
                            .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        taps.addTab("tab4", orderSummary);

        getContentPane().add(taps, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 860, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        customer.setName(txt_name.getText());
        customer.setCustomerId(Integer.parseInt(txt_id.getText()));
        customer.setAddress(txt_address.getText());
        taps.setSelectedIndex(1);
        name_in_receipt.setText(customer.getName());
        id_in_receipt.setText(Integer.toString(customer.getCustomerId()));
        address_in_receipt.setText(customer.getAddress());
        hi.setText("Hi,"+customer.getName());
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
    taps.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_place_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_place_orderActionPerformed
    taps.setSelectedIndex(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_place_orderActionPerformed

    private void btn_sumbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumbitActionPerformed
    thanku.setText("Done!");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sumbitActionPerformed

    private void plusbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbookActionPerformed
        booksnumber++;
        booknum.setText(Integer.toString(booksnumber));
        totalPrice+=p3.getPrice();
        total.setText("$"+Float.toString(totalPrice));
        booksPrice= booksnumber*p3.getPrice();
        total1.setText(total.getText());
        total2.setText(total.getText());
        total_book_price_cart.setText("$"+Float.toString(booksPrice));
        book_quantity_cart.setText(Integer.toString(booksnumber));
        total_book_price_cart1.setText("$"+Float.toString(booksPrice));
        book_quantity_cart1.setText(Integer.toString(booksnumber));
        // TODO add your handling code here:
    }//GEN-LAST:event_plusbookActionPerformed

    private void minbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minbookActionPerformed
        if (booksnumber>0) {
            booksnumber--;
            booknum.setText(Integer.toString(booksnumber));
            totalPrice-=p3.getPrice();
            total.setText("$"+Float.toString(totalPrice));
            booksPrice= booksnumber*p3.getPrice();
            total1.setText(total.getText());
            total2.setText(total.getText());
            total_book_price_cart.setText("$"+Float.toString(booksPrice));
            book_quantity_cart.setText(Integer.toString(booksnumber));
            total_book_price_cart1.setText("$"+Float.toString(booksPrice));
            book_quantity_cart1.setText(Integer.toString(booksnumber));

        } // TODO add your handling code here:
    }//GEN-LAST:event_minbookActionPerformed

    private void plustshirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plustshirtActionPerformed
        tshirtsnumber++;
        tshirtnum.setText(Integer.toString(tshirtsnumber));
        totalPrice+=p2.getPrice();
        total.setText("$"+Float.toString(totalPrice));
        tshirtsPrice= tshirtsnumber*p2.getPrice();
        total1.setText(total.getText());
        total2.setText(total.getText());
        total_tshirt_price_cart.setText("$"+Float.toString(tshirtsPrice));
        tshirt_quantity_cart.setText(Integer.toString(tshirtsnumber));
        total_tshirt_price_cart1.setText("$"+Float.toString(tshirtsPrice));
        tshirt_quantity_cart1.setText(Integer.toString(tshirtsnumber));

    }//GEN-LAST:event_plustshirtActionPerformed

    private void mintshirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mintshirtActionPerformed
        if (tshirtsnumber>0) {
            tshirtsnumber--;
            tshirtnum.setText(Integer.toString(tshirtsnumber));
            totalPrice-=p2.getPrice();
            total.setText("$"+Float.toString(totalPrice));
            tshirtsPrice= tshirtsnumber*p2.getPrice();
            total1.setText(total.getText());
            total2.setText(total.getText());
            total_tshirt_price_cart.setText("$"+Float.toString(tshirtsPrice));
            tshirt_quantity_cart.setText(Integer.toString(tshirtsnumber));
            total_tshirt_price_cart1.setText("$"+Float.toString(tshirtsPrice));
            tshirt_quantity_cart1.setText(Integer.toString(tshirtsnumber));

        }// TODO add your handling code here:
    }//GEN-LAST:event_mintshirtActionPerformed

    private void minphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minphoneActionPerformed
        if (phonesnumber>0) {
            phonesnumber--;
            phonenum.setText(Integer.toString(phonesnumber));
            totalPrice-=p1.getPrice();
            total.setText("$"+Float.toString(totalPrice));
            phonesPrice= phonesnumber*p1.getPrice();
            total1.setText(total.getText());
            total2.setText(total.getText());
            total_phone_price_cart.setText("$"+Float.toString(phonesPrice));
            phone_quantity_cart.setText(Integer.toString(phonesnumber));
            total_phone_price_cart1.setText("$"+Float.toString(phonesPrice));
            phone_quantity_cart1.setText(Integer.toString(phonesnumber));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_minphoneActionPerformed

    private void plusphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusphoneActionPerformed
        phonesnumber++;
        phonenum.setText(Integer.toString(phonesnumber));
        totalPrice+=p1.getPrice();
        total.setText("$"+Float.toString(totalPrice));
        phonesPrice= phonesnumber*p1.getPrice();
        total1.setText(total.getText());
        total2.setText(total.getText());
        total_phone_price_cart.setText("$"+Float.toString(phonesPrice));
        phone_quantity_cart.setText(Integer.toString(phonesnumber));
        total_phone_price_cart1.setText("$"+Float.toString(phonesPrice));
        phone_quantity_cart1.setText(Integer.toString(phonesnumber));
    }//GEN-LAST:event_plusphoneActionPerformed

    private void btn_tocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tocartActionPerformed
        if(phonesnumber+tshirtsnumber+booksnumber==0){
            error.setText("Add at least one product!");
        }else{
            error.setText(null);
            taps.setSelectedIndex(2);
        }

    }//GEN-LAST:event_btn_tocartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcommerceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcommerceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcommerceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcommerceSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcommerceSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address_in_receipt;
    private javax.swing.JLabel bookPrice;
    private javax.swing.JLabel book_quantity_cart;
    private javax.swing.JLabel book_quantity_cart1;
    private javax.swing.JLabel booknum;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_place_order;
    private javax.swing.JButton btn_sumbit;
    private javax.swing.JButton btn_tocart;
    private javax.swing.JLabel error;
    private javax.swing.JLabel errorLogin;
    private javax.swing.JLabel hi;
    private javax.swing.JLabel id_in_receipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private keeptoo.KGradientPanel login;
    private javax.swing.JButton minbook;
    private javax.swing.JButton minphone;
    private javax.swing.JButton mintshirt;
    private javax.swing.JLabel name_in_receipt;
    private keeptoo.KGradientPanel orderSummary;
    private javax.swing.JLabel phonePrice;
    private javax.swing.JLabel phone_quantity_cart;
    private javax.swing.JLabel phone_quantity_cart1;
    private javax.swing.JLabel phonenum;
    private javax.swing.JButton plusbook;
    private javax.swing.JButton plusphone;
    private javax.swing.JButton plustshirt;
    private keeptoo.KGradientPanel product;
    private javax.swing.JTabbedPane taps;
    private javax.swing.JLabel thanku;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    private javax.swing.JLabel total_book_price_cart;
    private javax.swing.JLabel total_book_price_cart1;
    private javax.swing.JLabel total_in_products;
    private javax.swing.JLabel total_in_products1;
    private javax.swing.JLabel total_in_products2;
    private javax.swing.JLabel total_phone_price_cart;
    private javax.swing.JLabel total_phone_price_cart1;
    private javax.swing.JLabel total_tshirt_price_cart;
    private javax.swing.JLabel total_tshirt_price_cart1;
    private javax.swing.JLabel tshirtPrice;
    private javax.swing.JLabel tshirt_quantity_cart;
    private javax.swing.JLabel tshirt_quantity_cart1;
    private javax.swing.JLabel tshirtnum;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private keeptoo.KGradientPanel yourCart;
    // End of variables declaration//GEN-END:variables
}
